### ISSUE TITLE
Anchor Platform Kubernetes Deployment

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#104]
Deploy Anchor Reference Server and Platform Servers to Kubernetes
GanttStart: 2022-04-04
GanttDue: 2022-04-21

**Comment by stfung77** [comment]
PR: https://github.com/stellar/kube/pull/805

**Comment by reecexlm** [comment]
you can link PR in the side panel as well.   Can you check with ops to see that the anchor validation tool will be able to hit this the deployed cluster.  (anchor platform docker).   this will prep us for using the validation tool to test our deployed platform. cc:  @JakeUrban
