### ISSUE TITLE
Observer doesn't handle payments for SEP-31 flow

### ISSUE THREAD

**Issue by rkharevych** [stellar/java-stellar-anchor-sdk#1056]
### What version are you using?
2.1.1

### What did you do?
Created `SEP-31` transaction and sent payment

### What happened?
Observer skipped my payment because it couldn't find `SEP-31` transaction by a combination of `memo` + `sourceAccount`, since `stellarAccountId` is actually `destinationAccount`(from payment):
![image](https://github.com/stellar/java-stellar-anchor-sdk/assets/131388170/08d498f5-73ae-4fd1-b93c-ad2d53abb4d3)
![image](https://github.com/stellar/java-stellar-anchor-sdk/assets/131388170/b73bac74-03fe-4252-837a-4bfa3b37bd97)

`SEP-24` withdrawal flow works fine because Observer tries to find `SEP-24` transaction by the same combination of `memo` + `sourceAccount`, but in this case `sep10Account` from `SEP-24` transaction is the same as `sourceAccount` from payment.
![image](https://github.com/stellar/java-stellar-anchor-sdk/assets/131388170/c2378c7d-735c-4f8c-acc0-ac12e8af2783)
![image](https://github.com/stellar/java-stellar-anchor-sdk/assets/131388170/08e3d033-9f11-4bb0-8be4-459a21d890c4)

### What did you expect to see instead?
- Observer correctly handled the payment
- Observer used `memo` + `destinationAccount` combination to find transaction for both `SEP-24` and `SEP-31` flows

**Comment by BenkikoDAO** [comment]
Looking forward to this being resolved as well.

> INFO
In the future, the Anchor Platform will also support making payments associated with deposit transactions to users on behalf of the business. This is another reason why you may want to use the Anchor Platform's event system.

**Comment by JakeUrban** [comment]
This was actually resolved https://github.com/stellar/java-stellar-anchor-sdk/pull/1090 and released in 2.2.2.
