### ISSUE TITLE
Validate Sep10, Sep12 with anchor validation tool

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#115]
Run platform server and reference server and verify SEP10 and SEP12 with https://anchor-tests.stellar.org/

**Comment by stfung77** [comment]
this is done and git issues have been filed
https://github.com/stellar/java-stellar-anchor-sdk/issues/142  (sep12)
https://github.com/stellar/java-stellar-anchor-sdk/issues/143  (sep10)
