### ISSUE TITLE
Anchor Platform Helm Chart

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#124]
as an anchor platform developer, I would like configuration template package for deploying anchor platform.  this story will be to create a helm chart and make available in help repository to make configuration of the anchor platform easy and compatible with helm package manager.

**Comment by stfung77** [comment]
We currently don't have Helm enabled in our K8s environment. We've opened a ticket with Ops to look into enabling this.
https://github.com/stellar/ops/issues/1624
