### ISSUE TITLE
Anchor Platform 1.X not working after Protocol 20 Upgrade

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#1244]
### What version are you using?
Hi SDF team! since the testnet reset our observer in preprod is stuck without reading new blocks. We already restarted it several times, but it doesn’t seems to unstuck it, we are on version release-1.2.19. Could this be related to the reset and do we need to upgrade to another version? Thanks!

[Logs_anchor-platform-observer-7ccd6794d-dq79k (1).txt](https://github.com/stellar/java-stellar-anchor-sdk/files/13814843/Logs_anchor-platform-observer-7ccd6794d-dq79k.1.txt)

**Comment by reecexlm** [comment]
SDF tracking internally with ANCHOR-576

**Comment by philipliu** [comment]
The previous cursor value is no longer valid after the Testnet reset. Once it was cleared from the database the observer continued processing new blocks.
