### ISSUE TITLE
env vars being exposed

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#1246]
This is exposing env vars. What can we do to avoid it / you should also disable it by default

[https://github.com/stellar/java-stellar-anchor-sdk/blob/9ccff3fd0ecd89cc9341cba434[…]a/org/stellar/anchor/reference/controller/HealthController.java](https://github.com/stellar/java-stellar-anchor-sdk/blob/9ccff3fd0ecd89cc9341cba43453b5bbaaf2c328/anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/HealthController.java#L25) 

![image](https://github.com/stellar/java-stellar-anchor-sdk/assets/98427531/b0644eb2-c5a7-4467-a740-67937a1536d9)
![image](https://github.com/stellar/java-stellar-anchor-sdk/assets/98427531/aa8137f6-9a4c-4aeb-a842-ff8f1b32944c)

**Comment by lijamie98** [comment]
The `anchor-reference-server` was the deprecated reference business server in Java and it had been deprecated.
