### ISSUE TITLE
Support `*_verification` fields in `PUT /customer` requests

### ISSUE THREAD

**Issue by JakeUrban** [stellar/java-stellar-anchor-sdk#1247]
### What problem does your feature solve?

SEP-12 includes a [`PUT /customer/verification`](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md#customer-put-verification) endpoint that is meant to accept verification of fields previously provided to `PUT /customer`, like `mobile_number` or `email_address`. However, the anchor platform doesn't support this endpoint, and it doesn't support accepting the `mobile_number_verification` or `email_address_verification` fields in `PUT /customer` requests.

### What would you like to see?

Instead of supporting `PUT /customer/verification`, allow the anchor to accept `*_verification` fields in `PUT /customer`, where `*` is a valid SEP-9 field. This will allow anchors implement a 2-step process where they first accept the field that requires verification and then request the verification of that field.

### What alternatives are there?

The alternative is to support the flow described in SEP-12, which is to set the field requiring verification to the `VERIFICATION_REQUIRED` status in `GET /customer` responses, and accept the verification with the `PUT /customer/verification` endpoint.

I don't think this is the best approach because we are trying to move away from using `GET /customer` as a means of determining which fields need to be provided to the anchor, in favor of the client polling the transaction record for which KYC may be required instead.

cc @Ifropc

**Comment by Ifropc** [comment]
Added proposal to simplify verification process using only `PUT /customer` endpoint: https://github.com/stellar/stellar-protocol/pull/1431

**Comment by Ifropc** [comment]
Tracked internally as ANCHOR-582
