### ISSUE TITLE
Feature Request: Add support for kafka SASL_SSL security protocol

### ISSUE THREAD

**Issue by ymatienzo** [stellar/java-stellar-anchor-sdk#1480]
### What problem does your feature solve?
Most kafka service providers require communication with the kafka cluster to be done via SASL_SSL. At this moment the event_processor does not support it. This makes it a challenge to configure the event_processor with kafka.

### What would you like to see?

adding support for SASL_SSL.

**Comment by lijamie98** [comment]
`SASL_SSL` is now supported since [2.11.1](https://github.com/stellar/java-stellar-anchor-sdk/releases/tag/2.11.1)
