### ISSUE TITLE
Fix configuration of the server deployed at https://anchor-sep-server-dev.stellar.org

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-anchor-sdk#172]
### What

Fix configuration of the server deployed at https://anchor-sep-server-dev.stellar.org

### Why

The SEP validator works fine with the preview image deployed at https://anchor-sep-pr{PR}.previews.kube001.services.stellar-ops.com but it fails with the server deployed from the master branch at https://anchor-sep-server-dev.stellar.org

Seems like the SEP-38 configuration is wrong for the production server.

**Comment by marcelosalloum** [comment]
Cc @reecexlm @stfung77

**Comment by stfung77** [comment]
could this be because the build deployed at anchor-sep-server-dev.stellar.org is running an older image that doesnt have the sep38 changes?

**Comment by marcelosalloum** [comment]
🤔  Maybe...
