### ISSUE TITLE
paymentservice: for each `payment-*` implementation, add documentation on how to use the SDK methods

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-anchor-sdk#23]
### What problem does your feature solve?
Since the fields used in `payment-*` implementations may not relate 100% 1:1 with the `PaymentsService` interface, we should have go-to documentation where devs can go to look for examples.

### What would you like to see?
A javadoc or a *.md file where users can quickly understand how to use the payments sdk.

### What alternatives are there?
❓

**Comment by marcelosalloum** [comment]
Cc @lijamie98, @reecexlm: do you know what's the best way to go about this in Java? Do devs usually rely on methods documentation or should we go with `*.md`?

Cc @JakeUrban

**Comment by lijamie98** [comment]
> Cc @lijamie98, @reecexlm: do you know what's the best way to go about this in Java? Do devs usually rely on methods documentation or should we go with `*.md`?
> 
> Cc @JakeUrban

@marcelosalloum Javadoc is only for API documentation. @JakeUrban is communicating to use gitbook which is a good place to explain how to use the payment service.

**Comment by JakeUrban** [comment]
Yup, I have a login to our Gitbook company account. I can create what they call a "Space" for the Java Stellar Anchor SDK, and can link it to this repository for documentation 👍

**Comment by JakeUrban** [comment]
Ok, the repo is linked! I'll ask Sandra to add both of you to the Gitbook account.

**Comment by marcelosalloum** [comment]
We've already adopted gitbook and the next step is to make sure we add documentation for `payments-circle` and `payments-stellar`.

`payments-circle` is in progress [here](https://github.com/stellar/java-stellar-anchor-sdk/pull/65) and I created a comment to address it for `payment-stellar` [here](https://github.com/stellar/java-stellar-anchor-sdk/pull/28#issuecomment-1048094397), so I'm closing this issue so we address the documentation in those links/tickets.
