### ISSUE TITLE
docker-compose for anchor-platform jar

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#242]
as an Anchor Platform user, adocker compose would be very useful for spinning up a more complete archItecture with kafka and postgres, for example. 
this task is to allow spinning up of all components using docker compose. it should include docker compose file, tested and updated readme documentation for usage.

**Comment by stfung77** [comment]
closed with PR https://github.com/stellar/java-stellar-anchor-sdk/pull/278
