### ISSUE TITLE
Rename `app-config` to `platform-config` in `anchor-config-defaults.xml` file.

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#243]
1. Change the value of `stellar.anchor.app-config.settings` to `platform-config`
2. Rename `app-config` to `platform-config`.

**Comment by reecexlm** [comment]
please pause this story to be coordinated with introduction of helm chart to preview pipeline so we can make sure the change is coordinated.  moving back to backlog
