### ISSUE TITLE
add end to end testing script to Github Actions CI/CD

### ISSUE THREAD

**Issue by stfung77** [stellar/java-stellar-anchor-sdk#249]
add a github action to execute the end to end tests (https://github.com/stellar/java-stellar-anchor-sdk/tree/main/end-to-end-tests) on PRs. 
these tests should block merging if they fail

**Comment by reecexlm** [comment]
could we consider not having this in Github actions and move into Jenkins Pipelines.  We want to be able to deploy different scenarios (eg integration auth JWT_TOKEN vs API_KEY) etc.   so meaning deploying different pipelines profiles and running the test.

**Comment by reecexlm** [comment]
[https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/docs/02%20-%20Cont[…]%20-%20End%20to%20End%20Testing%20with%20Different%20Configs.md](https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/docs/02%20-%20Contributing/G%20-%20End%20to%20End%20Testing%20with%20Different%20Configs.md)

**Comment by stfung77** [comment]
waiting on AP config refactoring before adding this to CI/CD

**Comment by marcelosalloum** [comment]
Closed by #536
