### ISSUE TITLE
SPIKE: Platform to Anchor Auth

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#264]
As an Anchor Platform Customer Anchor Platform and the Anchor Platform Reference server may run in different k8s clusters.  In these cases, mtls support may not be an option under that scenario. It would be preferred to hav API Key authentication.   This story is to  capture requirements and add issues to implement api key authentication between Anchor Platform (sep services) and Receiving Anchor application.

**Comment by stfung77** [comment]
do we want to use client attribution for this? https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#verifying-the-client-domain cc: @JakeUrban

**Comment by lijamie98** [comment]
client attribution is used to authentcate the wallet. I am not sure if it is proper to use SEP-10 authentication for this connection.

**Comment by stfung77** [comment]
+1 for mTLS

btw, we have an item for using TLS for server -> Kafka

**Comment by C0x41lch0x41** [comment]
[Using mTLS](https://medium.com/trendyol-tech/istio-mtls-between-multiple-clusters-b146829e40aa) is the preferred solution and remove the need to implement custom authentication logic at the application level.

**Comment by reecexlm** [comment]
This ticket now tracks implementing API Key Authentication

**Comment by marcelosalloum** [comment]
We should need two API keys, right?
- One for the callback API (`sync Platform->Anchor`)
- Another key for the Platform API (`sync Anchor->Platform`).

Is that what you had in mind @reecexlm, @C0x41lch0x41?

**Comment by marcelosalloum** [comment]
The recommendation @C0x41lch0x41 shared was:
* Use Jwt token in both sides with shared secrets.
* Use one secret for `sync Platform->Anchor` and another secret for `sync Anchor->Platform`.
