### ISSUE TITLE
External logging configurations

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#289]
**Problem:** 
Logging configuration is statically configured in [log4j2.yaml](https://github.com/stellar/java-stellar-anchor-sdk/blob/main/platform/src/main/resources/log4j2.yaml). 

**Solution:**
The location of `log4j2.yaml` should be overridable in the [`anchor-config.yaml`](https://github.com/stellar/java-stellar-anchor-sdk/blob/main/platform/src/main/resources/anchor-config-defaults.yaml#L52) similar to the way that we specify the location of the [`assets` JSON file](https://github.com/stellar/java-stellar-anchor-sdk/blob/main/platform/src/main/resources/anchor-config-defaults.yaml#L74).

**Comment by reecexlm** [comment]
@marcelosalloum will you be able to include splunk log appender with this story?

**Comment by marcelosalloum** [comment]
Seems like Splunk Log Appender will be handled in a separate ticket: https://github.com/stellar/java-stellar-anchor-sdk/issues/303

**Comment by lijamie98** [comment]
This issue is no longer valid because of the config refactoring #479 .
