### ISSUE TITLE
IAM Authentication for MSK

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#301]
Investigate supporting IAM based authentication for Anchor Platform deployed within Kubernetes to use AWS MSK Kafka.
For this ticket. Outline the technical design and estimate the Engineering Effort.  We can then determine priority/scheduling for implementation.

https://docs.aws.amazon.com/msk/latest/developerguide/security_iam_service-with-iam.html
https://www.amazonaws.cn/en/new/2021/introducing-iam-access-control-amazon-msk-china-regions/
https://github.com/aws/aws-msk-iam-auth

**Comment by stfung77** [comment]
closed with https://github.com/stellar/java-stellar-anchor-sdk/pull/356
