### ISSUE TITLE
High level Database Sizing

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#304]

**Comment by reecexlm** [comment]
As a Partner using the Anchor Platform, a database sizing guide will help to enable the proper back-end database infrastructure.  

This ticket will be to investigate generally the class of database infrastructure (CPU, IO, Memory) requirements.  Also provide high level sizing estimates (storage requirements).   Future stress testing will provide detailed sizing requirements.

**Comment by reecexlm** [comment]
will be added to documentation

**Comment by marcelosalloum** [comment]
I've executed the SEP-31+SEP-38 flow 492 times and here's the result:

* DB size right after created: **8649 kb**
* DB size right after migrations: **8921 kB**
* DB size after 48 SEP-31 transactions: **9129 kB**
  * 4.33 kB per SEP-31 transaction, derived from the formula `(9129-8921)/96 = 4.333`
* DB size after 300 SEP-31 transactions: **9625 kB**
  * 2.46 kB per SEP-31 transaction, derived from the formula `(9625-8921)/300 = 2.34666667`
* DB size after 492 SEP-31 transactions: **9889 kB**
  * 1.97kb kB per SEP-31 transaction, derived from the formula `(9889-8921)/492 = 1.96747967`

From this simulation, we can conclude the data occupied by each SEP-31 (with SEP-38) transaction tends to get smaller the more transactions are created, and it's roughly 2kb/transaction for 500 transactions.
