### ISSUE TITLE
IAM Authentication for Aurora

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#323]
As a Amazon Aurora users supported by Anchor Platform I would like to maintain centralized control of authentication credentials through IAM.  This issue will provide IAM authentication for Aurora enabling anchor platform user to not be required to maintain seperate set of credentials in anchor platform.
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html

**Comment by stfung77** [comment]
closed with https://github.com/stellar/java-stellar-anchor-sdk/pull/356
