### ISSUE TITLE
SEP-31: add sending anchor allowlist

### ISSUE THREAD

**Issue by JakeUrban** [stellar/java-stellar-anchor-sdk#365]
### What problem does your feature solve?

The current Java Anchor SDK / Anchor Platform code does not have any logic to deny an unapproved SEP-31 sending anchor.

[`app-config.sep10.omnibusAccountList`](https://github.com/stellar/java-stellar-anchor-sdk/blob/main/platform/src/main/resources/anchor-config-defaults.yaml#L129) is currently only used in relation to SEP-10 client attribution, and this SEP-10 feature is only utilized when Stellar accounts being authenticated are owned by individual users, not the applications / businesses themselves.

### What would you like to see?

This is up for debate. 

#### Option 1

One option is to add a configuration option that allows anchors to specify whether or not an allowlist should be checked whenever a Stellar account is authenticating via SEP-10. For anchors that only interact with applications that use omnibus accounts, this would be sufficient. 

`omnibusAccountList` could be checked if `requireKnownOmnibusAccount` (name TBD) is true, and clients would be rejected or accepted based on their public key's presence in the list. If `requireKnownOmnibusAccount` is false, the existing behavior would be used.

#### Option 2

The problem with Option 1 is that is doesn't account for the case where an anchor wants to restrict access to known SEP-31 senders but also allow access to noncustodial SEP-24 & 6 wallets. Clients do not specify the SEPs they intend to engage with when authenticating via SEP-10, and it would be a breaking change to start requiring that information.

Polaris deals with this by only restricting access to SEP-31 endpoints (excluding `GET /info`). Unknown accounts are still able to register customers via SEP-12 & create SEP-38 quotes, which are both actions necessary in SEP-6 flows.

We don't know if this would acceptable to anchors who only implement SEP-31, and the safe bet is to assume it would not be.

#### Option 3

We do both.

Add `requireKnownOmnibusAccount` to determine if `omnibusAccountList` should be used to gate access to all services. If `requireKnownOmnibusAccount` is false, the existing SEP-10 functionality implemented should be used. However, we can have another config option `knownSendingAnchorPublicKeyList` (name TBD), that is used to protect SEP-31 endpoints. 

### What alternatives are there?

I'm open to suggestions.

**Comment by marcelosalloum** [comment]
Since we're aiming at restricting SEP-31 senders, I prefer to go with a configuration that lives inside the SEP-31 scope only. Using SEP-10 configuration to restrict the behavior of SEP-31 sounds non-intuitive and it will lead to a complicated implementation and a complicated configuration for Platform integrators.

With that in mind, option 2 sounds like the way to go, IMO.

**Comment by spolaore** [comment]
Allowing unknown clients to be able to use SEP-12 and SEP-38, knowing we just want to provide SEP-31 capabilities, for the time being, is not something we'd prefer.

So if we had to choose in our current scenario, probably option #1 or #3.

**Comment by JakeUrban** [comment]
I think that since we only support SEP-31 in the platform currently, we can implement Option 1, and in the future add option 2 or an alternative in the future.
