### ISSUE TITLE
EPIC: Allow the pair `stellar_account:memo` to be generated by the Anchor backend

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-anchor-sdk#377]
### What

Include a way where the Platform can query the Anchor backend for the SEP-31 `account:(unique)memo` pair.

### Why

We need to have unique memos to correlate a Stellar payment to a SEP-31 transaction 1-to-1. The Platform currently allows for two methods of generating unique memos:
1. `depositInfoGeneratorType: self`, where the unique memo is generated by the Platform itself.
2. `depositInfoGeneratorType: circle`, where the Platform has access to a Circle API Key and can generate unique memos through the Circle API.

For some partners, none of those options is a fit, so we will need to allow these partners to create their own `account:memo`. This can happen through a HTTP request from `Platform->Anchor` to be incorporated in the [callback API](https://github.com/stellar/java-stellar-anchor-sdk/blob/b94b90816a1651163cc540f5e8d952119e793048/docs/03%20-%20Implementing%20the%20Anchor%20Server/Communication/Callbacks%20API.yml). This could be a new request or an update on the existing ones (TBD).

### Checklist
- [x] #379
- [x] #416
- [x] #182
- [x] #292
- [x] #294

**Comment by lijamie98** [comment]
Is #292 and #294 required to solve this ticket?

**Comment by marcelosalloum** [comment]
Actually not, they are more like nice-to-haves. 

Feel free to remove them from the checklist.

**Comment by marcelosalloum** [comment]
@lijamie98, @reecexlm: can this ticket be closed?
