### ISSUE TITLE
Validate anchor platform config

### ISSUE THREAD

**Issue by erika-sdf** [stellar/java-stellar-anchor-sdk#384]
### What problem does your feature solve?

Currently, there is no validation for incorrectly configured values in `anchor-config-defaults.yaml`. We discover the configuration is incorrect when the relevant operation fails.

### What would you like to see?

Add some validation logic for the config file on start up.

Initial criteria to consider:
* Is the parameter of the expected type (string, int, etc)?
* If a dependency on another SEP exist, is that SEP enabled?
* Do `classpath` files resolve?

**Comment by JakeUrban** [comment]
@erika-sdf where can I find the PR for this? I'd like to check it out
