### ISSUE TITLE
Sep 10 JWT Token Customer Filtering

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#401]

**Comment by reecexlm** [comment]
As a anchor platform developer, I want to make sure that only customers exposed are only those related to the SEP10 JWT Token that was authenticated.

**Comment by erika-sdf** [comment]
After chatting with @marcelosalloum and @lijamie98 about this, I think this runs into the same problem as Marcelo was running into last week, and attempted to address in [PR403](https://github.com/stellar/java-stellar-anchor-sdk/pull/403). Jamie mentioned kicking off a conversation about introducing a new platform-owned customer id
