### ISSUE TITLE
Enable Gitflow for Release Management

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#404]
As a developer of Anchor Platform there should be a clear separation of environments for 
Feature Development - next release
Bug Fixing - Production (hotfix), Current Release (Release under test)
Gitflow pattern enables such separation of concerns without blocking any development thread while also being clear what release is in each environment.
General principal
 Dev Branch (next release), Feature Branches (Branched off Dev)
 Master/Main Branch - current release in production
 Staging/Hotfix branch - matches master/main - used to fix bugs in production - create branch, fix and test bug, merge to master and backmerge to release/develop
 Release - branched off Dev for next release - used to perform integration testing before merge to main/master (cut release)
 bugs that occur in release and fixed, backmerged to develop (next release) possibly patched to production.

This story encompases: document our gitflow and gain agreement from team
socialize: allow product to review,ops review as well.
define story / tasks to enable (cicd environments, kubernetes namespaces, etc, github actions).

**Comment by marcelosalloum** [comment]
After we adopt `gitflow` we should start doing releases in the maven repository. This is related to:
- https://github.com/stellar/java-stellar-anchor-sdk/issues/299

**Comment by erika-sdf** [comment]
proposal: https://docs.google.com/document/d/1SUh1Bi83c3UIRhQW86eVWIUZDnpyQ-OozS4BTcF-kyA
