### ISSUE TITLE
bug: Platform attempts to connect to Kafka even if its disabled

### ISSUE THREAD

**Issue by JakeUrban** [stellar/java-stellar-anchor-sdk#429]
I’ve been trying to configure the platform to not use the event queue and I can’t get it to work. The app-config.event.enabled flag is false & I’ve commented out everything related to kafka but the anchor platform is still trying to connect to the Kafka port:

```
WARN  - o.a.k.c.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (localhost/127.0.0.1:29092) could not be established. Broker may not be available.
```

**Comment by spolaore** [comment]
I think we're seeing the same problem in our AWS env. 
Seems like kafka producers are ignoring the specified properties, this is blocking us from further testing.
