### ISSUE TITLE
clean up common-previews namespace

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#435]
many orphaned k8 resources no longer needed. lets remove them and make sure that deployments are cleaning up correctly.

**Comment by marcelosalloum** [comment]
Is this still an issue? All the images I see in common-previews refer to a PR that's still open.

<img width="700" alt="Screen Shot 2022-08-22 at 2 23 22 PM" src="https://user-images.githubusercontent.com/1952597/186021580-bfb5482b-d5df-464c-9174-926761309a46.png">
