### ISSUE TITLE
Platform rejects `POST /transactions` if `fields.transaction` is not present

### ISSUE THREAD

**Issue by JakeUrban** [stellar/java-stellar-anchor-sdk#449]
The demo wallet omits the inner `"transaction"` key in the `"fields"` object of the SEP-31 `POST /transactions` request. This is technically a bug in the demo wallet, so we should probably fix that.

However, the Platform rejected this request with a 400, which I think is a bit heavy handed. Per-transaction fields are optional, so why should the platform reject requests that don't have an empty `fields.transaction` object?

Request:

<img width="450" alt="Screen Shot 2022-08-01 at 10 47 17 AM" src="https://user-images.githubusercontent.com/10968980/182211127-fba91a24-fd32-4336-a4a6-3ecdb8b859f9.png">

Error log:

```
17:45:44.712 INFO  - o.s.a.s.Sep31Service - 'fields' field must have one 'transaction' field for request (Sep31PostTransactionRequest(amount=10, assetCode=SRT, assetIssuer=null, destinationAsset=null, quoteId=null, senderId=8382897963409874535, receiverId=8295117905575523054, fields=Sep31PostTransactionRequest.Sep31TxnFields(transaction=null), lang=null))
```

**Comment by reecexlm** [comment]
adding to our backlog. thanks for catching this!
