### ISSUE TITLE
create script to recreate all testnet assets and accounts used by Anchor Platform

### ISSUE THREAD

**Issue by stfung77** [stellar/java-stellar-anchor-sdk#471]
### What problem does your feature solve?
after testnet resets, we have to manually recreate all accounts and assets used by the Anchor Platform.

### What would you like to see?
create script to recreate all testnet assets and accounts used by Anchor Platform and see if ops can run this script after testnet resets

**Comment by marcelosalloum** [comment]
Posting this comment here for reference: https://github.com/stellar/java-stellar-anchor-sdk/pull/464#discussion_r939448521
