### ISSUE TITLE
Make sure to cover the SEP-31 refund flow

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-anchor-sdk#473]
### What problem does your feature solve?
Make sure the Platform is covering the SEP-31 refunds flow.

### What would you like to see?
Integration and unit tests in place to make sure the flow is being covered. This may lead to updated in the code.

**Comment by nirojapanda** [comment]
Refund additional use case - Clabe # is valid but not accepted by Mexican bank

**Comment by marcelosalloum** [comment]
We should add a unit test for this.
