### ISSUE TITLE
Configuration File Refactor

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#478]
As an Anchor Platform developer,  a simplified and minimal configuration file is desirable to make getting up and running easier.

This story is to refactor our yaml configuration file and make the default configuration file simple, with less required parameters so that getting up and running is quick and easy.   Advanced configuration can be added if required.  

The deliverable for this story will be a new simplified version of yaml configuration.  Some points discussed include
- make nested configuration easy to understand 
- eliminate config redirection, eg our current app_config (or database) stanza which points to another yaml configuration. 
- add documentation to yaml file
- comment out whatever is not needed
- include "basic" section with minimal parameters
- datadog [agent configuration file](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml) may be a good example of this 
- remove need for ENV var tokens/placeholders - work in conjunction with configuration source class issue to read from env_var based on parameter name. 

produce a sample configuration file and get review from team via PR comments.

**Comment by nirojapanda** [comment]
@reecexlm  to merge this with #479 and close this
