### ISSUE TITLE
Configuration management refactoring

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#479]
As a Anchor Platform Developer I would like to have a configuration management experience that is easy to use, quick to get up and running to test, and easy to troubleshoot.  This story provides the configuration processing class to support the new (simiplified) configuration file and make it easy to know how the AP is processing configuration for troubleshooting

Points for this story include:
- produce the anchor platform configuration source class to process configuration file and load runtime configuration
- support environment variable/secret handling
- enable debug logging for processing steps (eg, tried to read from file, loaded from env_var, etc) so its easy to troublshoot how configuration was processed in detailed manner
- include integration testing for configuraitons

**Comment by lijamie98** [comment]
This is in progress: https://github.com/stellar/java-stellar-anchor-sdk/pull/516
