### ISSUE TITLE
Investigate how to turn off flyway auto-apply features

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-anchor-sdk#528]
### What the problem is

Flyway currently auto-migrates by default. I've tested it with a local postgres database and noticed that if I set the configuration `spring.flyway.enabled: false`, the database still gets auto-updated.

The weirdest thing is that the database gets updated beyond the migration files. Meaning that if we have new JPA Entities in the code and we don't have migrations to add them, they get auto-created in the Postgres database.

### What's the expected behavior

This behavior should be disabled by default.

In reality, we just want the software to go as far as applying the migration but never applying changes that are not even in the migrations. Even migrations should only be applied if explicitly configured by the user.

**Comment by stfung77** [comment]
close with: https://github.com/stellar/java-stellar-anchor-sdk/pull/532
