### ISSUE TITLE
Spike: Sep-24 Requirements

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#537]
As an Anchor Platform engineer, I would like to determine the requirements for AP SEP-24 Implementation and flush out design/implementation tasks.

**Comment by lijamie98** [comment]
Here is the rough plan to implement SEP-24 in Anchor Platform

1. Review the gap between [SEP-24 specification](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md) and [Sep24Service.java](https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/core/src/main/java/org/stellar/anchor/sep24/Sep24Service.java).
2. Create issues and implement
3. Patch [Sep24ServiceTest.kt](https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt) and maintain 100% coverage.
4. Implement Sep24Integration test in CI
5. Enable [stellar-anchor-tests](https://github.com/stellar/java-stellar-anchor-sdk/blob/develop/.github/workflows/basic_tests.yml#L65) SEP-24 test in basic tests.
6. Harden and clean up core library Maven Central publication process with Github secrets.
7. Start working with MGI to integrate with the main branch.
8. Migrate MGI integration to Maven Central integration.

**Comment by lijamie98** [comment]
+ @brunomuler @nirojapanda @nickgilbert
