### ISSUE TITLE
Gradle task to guarantee that everything from anchor-config-schema-v1.yaml is in anchor-config-default-values.yaml

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#580]
From PR #516

**Comment by marcelosalloum** [comment]
Relevant to the comment https://github.com/stellar/java-stellar-anchor-sdk/pull/516#discussion_r975711029

**Comment by marcelosalloum** [comment]
Since we have many deployment environments (and many example files for end0tio-end tests, helm, fargate, k8s, etc), it'd be great to have a script that checks if we remembered to update all of these resources when we update a schema.

**Comment by marcelosalloum** [comment]
@lijamie98 suggested this could be even simpler, by adding this check to the unit tests.
