### ISSUE TITLE
Feature Request: Enable integration with Fireblocks.

### ISSUE THREAD

**Issue by ymatienzo** [stellar/java-stellar-anchor-sdk#625]
Hi guys, 

could you tell me what is the best way to contribute to the Fireblocks integration? During Meridian @JakeUrban told me that you guys where planning/working on it. But I could not find any folder in the project code about it. Let me know.

**Comment by reecexlm** [comment]
hi @ymatienzo  we have added Fireblocks support in [Anchor Platofrm 2.3.0](https://github.com/stellar/java-stellar-anchor-sdk/releases/tag/2.3.0) Custody Services. Here are the [docs](https://developers.stellar.org/docs/category/custody-services).   Let us know if this meets your needs!
