### ISSUE TITLE
Anchor-platform searches for wrong customertype to validate if the receiver exists.

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#717]
We configured a new receiving customer type, on top of our pre existing receiving_user .When
 using the id of this new customer type created to call transactions and I am receiving that the customer does not exist. Looking into the logs, I see this:

```Unable to find customer FindCustomer(id=*******, account=null, memo=null, type=receiving_user) due to Failure(code=customer.not.found, reason=, details=[], cause=Optional.empty, i18nData=Failure.I18nData(code=failure.i18.default, defaultMessage=, arguments=[]))

**Comment by reecexlm** [comment]
https://stellarfoundation.slack.com/archives/C023KRRF5C4/p1674507642413909

**Comment by Ifropc** [comment]
Fixed in #721
