### ISSUE TITLE
Anchor Platform Docker Container

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#83]
as an anchor server engineering, i would like to build a docker image the anchor reference server. For this task

enable building of docker image
test docker image locally
enable integration test to optionally use reference server docker image instead of local process
GanttStart: 2022-03-11
GanttDue: 2022-03-14

**Comment by JakeUrban** [comment]
We at least two docker containers for this task. The first is the Anchor Platform container, the 2nd is the reference server container that sits behind the anchor platform. Does that match what you were envisioning @reecexlm ?

**Comment by stfung77** [comment]
added Dockerfile and updated docs [7b01fc3](https://github.com/stellar/java-stellar-anchor-sdk/commit/7b01fc377551309976dbaba105f56ad732098961)

@lijamie98 is working on tests and i'll sync up with him tomorrow on running this against the image

**Comment by stfung77** [comment]
GH action is set up to build and push images to https://hub.docker.com/r/stellar/anchor-platform/tags

**Comment by reecexlm** [comment]
great. will close this issue
