### ISSUE TITLE
MSK on Anchor Platform failed to construct kafka producer

### ISSUE THREAD

**Issue by shuangqiu123** [stellar/java-stellar-anchor-sdk#861]
### What version are you using?
2.0.0-rc.1 
MSK Kafka 3.2.0 with IAM Authentication

### What did you do?
Start Anchor Platform on AWS ECS Container. 

### What happened?
The Kafka producer failed to construct because of the JAAS config. The error log is below:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'platformController' defined in URL [jar:file:/app/anchor-platform-runner.jar!/BOOT-INF/lib/platform-2.0.0-rc.1-plain.jar!/org/stellar/anchor/platform/controller/sep/PlatformController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'transactionService' defined in class path resource [org/stellar/anchor/platform/component/sep/PlatformApiBeans.class]: Unsatisfied dependency expressed through method 'transactionService' parameter 4; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventService' defined in class path resource [org/stellar/anchor/platform/component/share/EventBeans.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.stellar.anchor.event.EventService]: Factory method 'eventService' threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka producer

Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer 
Caused by: java.lang.IllegalArgumentException: Login module control flag not specified in JAAS config
at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:110) ~[kafka-clients-3.3.1.jar!/:?]

Here is the config for the MSK on the anchor platform
events:
  enabled: true
  event_type_to_queue:
    quote_created: ap_event_quote_created
    transaction_created: ap_event_transaction_created
    transaction_status_changed: ap_event_transaction_status_changed
    transaction_error: ap_event_transaction_error
  publisher:
    type: msk
    msk:
      use_IAM: true

### What did you expect to see instead?
It should work normally.

**Comment by reecexlm** [comment]
Hi @shuangqiu123 is this still an issue for you? Could you please be sure to use the latest version.  Thank you.

**Comment by Ifropc** [comment]
Closing as stale. Please feel free to create a new issue if you are still having problems using the latest version of the platform
