### ISSUE TITLE
Documentation problems

### ISSUE THREAD

**Issue by DomenicoGagliano** [stellar/java-stellar-anchor-sdk#868]
I am trying to follow the steps described on the documentation to run the anchor services locally. Unfortunately what described has missing correspondence on the code.
- The command cd docs/resources/docker-examples/kafka && docker compose up to start the Kafka Queue service does not work because there is no docs/resources/docker-examples/kafka directory therefore there is no docker-compose file to run.
- The file example.env that should be used for the environment variables is missing (the link in the documentation returns error 404), so the command ./gradlew service-runner:bootRun --args=--sep-server fails because the following variables are not defined:
   - SECRET_DATA_USERNAME
   - SECRET_DATA_PASSWORD
   - SECRET_SEP10_SIGNING_SEED
   - SECRET_SEP10_JWT_SECRET
   - SECRET_SEP24_INTERACTIVE_URL_JWT_SECRET
   - SECRET_SEP24_MORE_INFO_URL_JWT_SECRET

If I want to run the services as described in "Running the Application with Docker Compose", there is no docker-compose file to run (again, the link in the documentation returns error 404)

Could you please check what's not correct with the documentation and if necessary resume the missing files?

**Comment by Ifropc** [comment]
Hi @DomenicoGagliano , thank you for having an interest in the Platform.
Current README docs are heavily outdated. This is something that will be addressed in the near future.
Up to date documentation is available at the [docs.stellar.org website ](https://developers.stellar.org/docs/anchoring-assets/anchor-platform/)
